---
broker:
  # The topic to which the producer will send messages
  topic: "auth.auditEvent.received"
  seeds:
    # The Kafka broker address
    - "localhost:9092"
  sasl:
    # Enable SASL authentication
    enabled: true
    # Username for SASL authentication
    username: 'emm'
    # Password for SASL authentication
    password: 'ocs'
pool:
  # Number of worker threads to process messages
  num_workers: 1
  # Number of messages to process in each batch
  messagesPerBatch: 10
  # Number of batches to process before stopping
  batches: 1
  # Number of errors allowed before stopping the worker
  errorThreshold: 2
